[package]
name = "bdwgc-example"
version = "0.1.0"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2018"

[dependencies]
bdwgc-alloc = "0.2"
tokio = { version = "0.1.18", features = ["async-await-preview"] }
tokio-async-await = { version = "0.1.6" }
